-- Создание таблицы "фильмы"

CREATE TABLE movies (
movie_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR(255) NOT NULL,
overview VARCHAR(1000) NOT NULL UNIQUE,
release_date DATE NOT NULL,
duration INT NOT NULL,
budget INT NOT NULL,
revenue BIGINT DEFAULT NULL,
vote_average DECIMAL(4,2) NOT NULL CHECK (vote_average > 0.0 and vote_average < 10.0)
);

-- Создание таблицы "страны" и связующей

CREATE TABLE countries (
country_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
country_name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE movie_countries (
movie_id INT REFERENCES movies (movie_id) NOT NULL,
country_id INT REFERENCES countries (country_id) NOT NULL
);

-- Создание таблицы "языки" и связующей

CREATE TABLE languages (
language_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
language_name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE movie_languages (
movie_id INT REFERENCES movies (movie_id) NOT NULL,
language_id INT REFERENCES languages (language_id) NOT NULL
);

-- Создание таблицы "Жанры" и связующей

CREATE TABLE genres (
genre_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
genre_name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE movie_genres (
movie_id INT REFERENCES movies (movie_id) NOT NULL,
genre_id INT REFERENCES genres (genre_id) NOT NULL
);

-- Создание таблицы "Производственная компания" и связующей

CREATE TABLE production_companies (
company_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
company_name VARCHAR(255) NOT NULL CHECK (company_name !='')
);

CREATE TABLE movie_companies (
movie_id INT REFERENCES movies (movie_id) NOT NULL,
company_id INT REFERENCES production_companies (company_id) NOT NULL
);

-- Создание таблицы "Люди"

CREATE TABLE person (
person_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
person_name VARCHAR(255) NOT NULL CHECK (person_name !='')
);

-- Создание таблицы "Съемочная группа"

CREATE TABLE movie_crew (
movie_id INT REFERENCES movies (movie_id) NOT NULL,
person_id INT REFERENCES person (person_id) NOT NULL,
job VARCHAR(255) NOT NULL
);

-- Создание таблицы "Актерский состав"

CREATE TABLE movie_cast (
movie_id INT REFERENCES movies (movie_id) NOT NULL,
person_id INT REFERENCES person (person_id) NOT NULL,
character_name VARCHAR(255) NOT NULL
);

